version: "3.8"
name: "cremusic"

services:
  postgresql:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  cremusic:
    build:
      context: .
      dockerfile: Dockerfile
    image: cremusic
    restart: "always"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgresql
    expose:
      - "8000"
    depends_on:
      - postgresql

  nginx:
    image: public.ecr.aws/docker/library/nginx:1.21-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    restart: "always"


# vim:set et sw=2 ts=2 tw=120 ft=docker-compose.yaml:
