version: "3.8"
name: "cremusic"

services:
  postgresql:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=pokemon
