"""statisticlog_phone_code_unique

Revision ID: 0b153ca782d7
Revises: 844cf6ff79e5
Create Date: 2023-05-25 23:43:40.299560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b153ca782d7'
down_revision = '844cf6ff79e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'statistic_log', ['telephone', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistic_log', type_='unique')
    # ### end Alembic commands ###
