"""modified_date_nullable

Revision ID: 8f21be834dfd
Revises: cb16919f71c4
Create Date: 2023-05-22 23:13:12.655139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f21be834dfd'
down_revision = 'cb16919f71c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('book_episode', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_episode', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('book', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
