"""fix_sequences

Revision ID: ab860731b7b4
Revises: b2c422733458
Create Date: 2023-08-28 14:55:05.854268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab860731b7b4'
down_revision = 'b2c422733458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql = [
        "SELECT SETVAL('public.book_code_id_seq', COALESCE(MAX(id), 1) ) FROM public.book_code;",
        "SELECT SETVAL('public.book_episode_id_seq', COALESCE(MAX(id), 1) ) FROM public.book_episode;",
        "SELECT SETVAL('public.book_episode_video_id_seq', COALESCE(MAX(id), 1) ) FROM public.book_episode_video;",
        "SELECT SETVAL('public.book_id_seq', COALESCE(MAX(id), 1) ) FROM public.book;",
        "SELECT SETVAL('public.config_id_seq', COALESCE(MAX(id), 1) ) FROM public.config;",
        "SELECT SETVAL('public.statistic_log_id_seq', COALESCE(MAX(id), 1) ) FROM public.statistic_log;",
    ]
    op.execute(sa.text('\n'.join(sql)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
