"""initial

Revision ID: 70981ff17fee
Revises: 
Create Date: 2023-05-17 22:43:48.043478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70981ff17fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('background_image_url', sa.String(length=1024), nullable=False),
    sa.Column('background_color_code', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=256), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_unlock', sa.Boolean(), nullable=False),
    sa.Column('global_code', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('test', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('telephone', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('release_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('book_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('background_image_url', sa.String(length=1024), nullable=True),
    sa.Column('background_color_code', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=256), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_episode_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_episode_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_episode_id'], ['book_episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_episode_video')
    op.drop_table('book_episode')
    op.drop_table('book_code')
    op.drop_table('statistic_log')
    op.drop_table('config')
    op.drop_table('book')
    # ### end Alembic commands ###
