"""book_not_require_unlock

Revision ID: b2c422733458
Revises: 2c65e1747817
Create Date: 2023-06-02 21:49:06.606916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c422733458'
down_revision = '2c65e1747817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('not_require_unlock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'not_require_unlock')
    # ### end Alembic commands ###
