"""config

Revision ID: 844cf6ff79e5
Revises: 8f21be834dfd
Create Date: 2023-05-22 23:15:19.528680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844cf6ff79e5'
down_revision = '8f21be834dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
